Allow building the Gitlab docker image in Gitlab (#8507)
## Summary of changes

- Moves the building of GitLab image into GitLab
- Updates the build images/runners to use Windows 2022

## Reason for change

Today, updating the windows gitlab image involves
- building the image locally
- pushing it to dockerhub
- testing the image works
- making a PR to Datadog/images to mirror the image
- Updating the original PR to use the new image

That's a lot of faff. Instead, this PR changes it so that building the
docker image is just "click a button in GitLab"

## Implementation details

The crux of the implementation uses a hash of the contents of the gitlab
dockerimage folder. There's other ways we could do this, but this has
the nice behaviour of meaning your build will fail if you change
something there and _don't_ rebuild the image (e.g. see #8474).

The first time you change something in this folder, [the `Build` stage
will
fail](https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-dotnet/-/jobs/1621141095):

```
ERROR: Windows build image not found at registry.ddbuild.io/ci/dd-trace-dotnet/dd-trace-dotnet-docker-build:d8e89e5cffc8.
The Dockerfile or install scripts under tracer/build/_build/docker/gitlab/ have changed.
Manually trigger the 'build-windows-ci-image' job in this pipeline, wait for it to finish, then re-run this job.
```

You can then click on the pipeline, click
[build-windows-ci-image](https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-dotnet/-/jobs/1621141094),
and go make a coffee ☕ After ~45 mins, the new image should have been
pushed, and you can re-run the build, with your new changes.

## Test coverage

I tested the workflow for this PR, and it works 🙌 

## Other details

One issue I had to deal with is the 2019/2022 issue. You can only run
docker images of the same base Windows version on the host, and the
`registry.ddbuild.io/ci-identities/ci-identities-gitlab-job-client:v0.2.0-windows-amd64`
image is apparently a 2022 host. Seeing as we really should be using
2022 anyway (and we use 2022 in azure devops), switched everything to be
2022 instead