Fix TagsListTests flakiness (#6823)
## Summary of changes

These tests were randomly failing in the CI:
TagsListTests.Serialization_RootSpan
TagsListTests.Serialization_ServiceEntrySpan
TagsListTests.Serialization_ChildSpan()

In all the cases, the error message was similar:
Exception: Expected deserializedSpan.Tags to contain 20 item(s), but
found 30:

The extra tags were debugger tags such as _dd.code_origin.type

If we look at the logs messages, we can see that the debugger tests were
running at the same time when errors occurred:

```
 2025-04-02T15:19:35.2989553Z 15:19:35 [DBG] [xUnit.net 00:00:08.11] Datadog.Trace.Tests: STARTED: Datadog.Trace.Tests.Debugger.SpanCodeOriginTests.SetCodeOrigin_WhenDisabled_DoesNotSetTags()
2025-04-02T15:19:35.3088642Z 15:19:35 [DBG] [xUnit.net 00:00:08.13] Datadog.Trace.Tests: SUCCESS: Datadog.Trace.Tests.Debugger.SpanCodeOriginTests.SetCodeOrigin_WhenDisabled_DoesNotSetTags() (0.0186219s)
2025-04-02T15:19:35.3089389Z 15:19:35 [DBG] [xUnit.net 00:00:08.13] Datadog.Trace.Tests: STARTED: Datadog.Trace.Tests.Debugger.SpanCodeOriginTests.SetCodeOrigin_WithMaxFramesLimit_RespectsLimit()
2025-04-02T15:19:35.3209962Z 15:19:35 [DBG] [xUnit.net 00:00:08.14] Datadog.Trace.Tests: SUCCESS: Datadog.Trace.Tests.Debugger.SpanCodeOriginTests.SetCodeOrigin_WithMaxFramesLimit_RespectsLimit() (0.012163s)
2025-04-02T15:19:35.3210678Z 15:19:35 [DBG] [xUnit.net 00:00:08.14] Datadog.Trace.Tests: STARTED: Datadog.Trace.Tests.Debugger.SpanCodeOriginTests.SetCodeOrigin_WhenEnabled_SetsCorrectTags()
 2025-04-02T15:19:35.3305251Z 15:19:35 [DBG] [xUnit.net 00:00:08.15] Datadog.Trace.Tests: STARTED: Datadog.Trace.Tests.Tagging.TagsListTests.Serialization_ServiceEntrySpan()
2025-04-02T15:19:35.3453136Z 15:19:35 [DBG] [xUnit.net 00:00:08.16] Datadog.Trace.Tests: SUCCESS: Datadog.Trace.Tests.Debugger.SpanCodeOriginTests.SetCodeOrigin_WhenEnabled_SetsCorrectTags() (0.0234982s)
2025-04-02T15:19:35.3453886Z 15:19:35 [DBG] [xUnit.net 00:00:08.16] Datadog.Trace.Tests: STARTED: Datadog.Trace.Tests.Debugger.SpanCodeOriginTests.SetCodeOrigin_WhenSpanIsNull_DoesNotThrow()
2025-04-02T15:19:35.3467906Z 15:19:35 [DBG] [xUnit.net 00:00:08.17] Datadog.Trace.Tests: SUCCESS: Datadog.Trace.Tests.Debugger.SpanCodeOriginTests.SetCodeOrigin_WhenSpanIsNull_DoesNotThrow() (0.0020212s)
2025-04-02T15:19:35.3862361Z 15:19:35 [DBG] [xUnit.net 00:00:08.18] Datadog.Trace.Tests: FAILURE: Datadog.Trace.Tests.Tagging.TagsListTests.Serialization_ServiceEntrySpan() (0.0320483s)
```

The reason is that TagsListTests were eventually calling this method
from the SpanCodeOriginManager class:
```
        internal void SetCodeOrigin(Span? span)
        {
            if (span == null || !_settings.CodeOriginForSpansEnabled)
            {
                return;
            }

            AddExitSpanTag(span);
        }
```

This code adds some extra debugger tags if
settings.CodeOriginForSpansEnabled. It is invoked for a static instance,
from the tracer class, StartSpan method.

`SpanCodeOriginManager.Instance.SetCodeOrigin(span);`

In DebuggerSettingsTests, the setting CodeOriginForSpansEnabled of
SpanCodeOriginManager.Instance is enabled in some tests, changing the
static instance settings values. Since both test classes are using the
same static instance, changes are shared.

This PR prevents this behavior by using local instances of
SpanCodeOriginManager in DebuggerSettingsTests instead of the static
one. This change also simplifies the tests.

In TagsListTests.cs, Count.Should().Be occurrences have been changed to
Should().HaveCount because this one is more verbose when an error
occurs, showing the contents of the collection.

## Reason for change

## Implementation details

## Test coverage

## Other details
<!-- Fixes #{issue} -->

<!-- ⚠️ Note: where possible, please obtain 2 approvals prior to
merging. Unless CODEOWNERS specifies otherwise, for external teams it is
typically best to have one review from a team member, and one review
from apm-dotnet. Trivial changes do not require 2 reviews. -->