Capture Exception when sending metrics (#7614)
## Summary of changes

We are getting some [test
errors](https://app.datadoghq.com/ci/test/runs?query=test_level%3Atest%20%40test.service%3Add-trace-dotnet%20%40test.status%3Afail%20%40git.branch%3Amaster%20%40test.full_name%3A%2ACouch%2A&agg_m=count&agg_m_source=base&agg_t=count&currentTab=overview&eventStack=AwAAAZmlUDfVUlPy2QAAABhBWm1sWG5pQUFBQkRidXJUT3YtMjlsbEgAAAAkZjE5OWE1NTEtYjcxYi00ZTNjLWE4MjQtMzk3OWJkMWZmNWFlAAHSfw&fromUser=false&index=citest&testId=AwAAAZmlUDfVUlPy2QAAABhBWm1sWG5pQUFBQkRidXJUT3YtMjlsbEgAAAAkZjE5OWE1NTEtYjcxYi00ZTNjLWE4MjQtMzk3OWJkMWZmNWFlAAHSfw&trace=AwAAAZmlUDfVUlPy2QAAABhBWm1sWG5pQUFBQkRidXJUT3YtMjlsbEgAAAAkZjE5OWE1NTEtYjcxYi00ZTNjLWE4MjQtMzk3OWJkMWZmNWFlAAHSfw&start=1758882011475&end=1759486811475&paused=false)
because the flaky attributte sends some telemetry reporting the flaky
test failures and, when the telemetry call fails, en exception is thrown
and the test itself fails as well.

```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
---- System.IO.IOException : Received an unexpected EOF or 0 bytes from the transport stream.
```

This error can make any test using telemetry fail if the telemetry
endpoint does not respond, for instance, so it can potentially affect
many tests.

## Reason for change

## Implementation details

## Test coverage

## Other details
<!-- Fixes #{issue} -->


<!--  ⚠️ Note:

Where possible, please obtain 2 approvals prior to merging. Unless
CODEOWNERS specifies otherwise, for external teams it is typically best
to have one review from a team member, and one review from apm-dotnet.
Trivial changes do not require 2 reviews.

MergeQueue is NOT enabled in this repository. If you have write access
to the repo, the PR has 1-2 approvals (see above), and all of the
required checks have passed, you can use the Squash and Merge button to
merge the PR. If you don't have write access, or you need help, reach
out in the #apm-dotnet channel in Slack.
-->

---------

Co-authored-by: Steven Bouwkamp <steven.bouwkamp@datadoghq.com>