Allow forcing interface duck types to be classes, and update Datadog.Trace.Manual (#6082)
## Summary of changes

- Add duck typing feature to force creating class-based proxies for
interfaces instead of structs
- Update all duck-typed interfaces in Datadog.Trace.Manual to use
class-based proxies

## Reason for change

In #6073, a customer was using the return type of manual instrumentation
(`IScope`) in an expression (as part of
[Lamar's](https://jasperfx.github.io/lamar/) IoC implementation). This
was causing an error in the expression:

```
System.ArgumentException: Expression of type 'Datadog_Trace__DEF86D061D0D2EEB.Datadog_Trace_Scope.Datadog_Trace_IScope_26' cannot be used for parameter of type 'Datadog.Trace.IScope' of method 'Void set_DatadogScope(Datadog.Trace.IScope)' (Parameter 'arg0')
```

Ultimately, it's because `Expression.Call()` invokes
`TypeUtils.AreReferenceAssignable()` which always return `false` for
struct types:
https://github.com/dotnet/runtime/blob/cf258a14b70ad9069470a108f13765e0e5988f51/src/libraries/System.Linq.Expressions/src/System/Dynamic/Utils/TypeUtils.cs#L851

We can confirm this using:

```csharp
var scope = Datadog.Trace.Tracer.Instance.StartActive("Hello");
Console.WriteLine(scope.GetType());

var type = Type.GetType("System.Dynamic.Utils.TypeUtils, System.Linq.Expressions");

var areReferenceAssignable = type
    .GetMethod("AreReferenceAssignable", BindingFlags.Static | BindingFlags.Public);

Console.WriteLine(areReferenceAssignable.Invoke(null, [ typeof(IScope), scope.GetType()])); // false
```

A minimal repro (when auto instrumentation is enabled) looks like this:

```csharp
Expression.Call(
    typeof(Program).GetMethod("CallMe", BindingFlags.Static | BindingFlags.NonPublic),
    Expression.Constant(Datadog.Trace.Tracer.Instance.StartActive("Hello")));

static void CallMe(IScope scope) => Console.WriteLine("Hello world!");
```

This behaviour seems weird, but the only obvious solution to it is to
use classes instead of structs for our proxies in cases where we're
publicly exposing the proxies.

Overall, this shouldn't have any actual impact on performance; we're
returning `IScope` etc anyway, which requires boxing our duck types.

## Implementation details

Add a `[DuckAsClass]` attribute that can only be applied to interfaces.
The `DuckType` class checks for this attribute (or a similarly named
attribute) when creating the proxy, and uses a class-based proxy if
required.

Subsequently added the `[DuckAsClass]` to the following interfaces (all
the public interfaces) in the _Datadog.Trace.Manual_ project:

- `ITest`
- `ITestModule`
- `ITestSession`
- `ITestSuite`
- `IScope`
- `ISpan`
- `ISpanContext`
- ~`ITracer`~ This isn't used from duck typing so doesn't need it


## Test coverage

- Added unit tests for the duck typing `[DuckAsClass]` attribute.
- Added reproduction/regression tests for manual instrumentation

## Other details

Fixes #6073