Add exceptions to active span during ASP.NET Web API 2 message handler exception (#1734)
## Scenario
At least one scenario has been identified today where an exception is thrown during while handling an ASP.NET Web API 2 request and we are unable to attach the error to our automatic instrumentation spans. This occurs when the application registers custom message handlers in the ASP.NET Web API 2 and the message handlers throw exceptions (before reaching the Api controllers). The result is that there was no `aspnet-webapi.request` span and the `aspnet.request` root span only sees the 500 status code because the exception was handled by the ASP.NET Web API 2 pipeline before returning.

## Fix
Add an automatic instrumentation method into the global error handling of ASP.NET Web API 2 applications. When an exception is detected by the Web API 2 pipeline, the registered `IExceptionHandler` singleton is invoked before returning the request to the server, so we hook into that call to grab the exception object and attach it to the active span.

Note: This exception handling also applies to OWIN applications running Web API 2 endpoints, so once we automatically instrument OWIN applications to generate root spans this feature will come along for free.

### Before
```
Tags: {
  error.msg: The HTTP response has status code 500.
}
```

### After
```
Tags: {
      error.msg: Passed in value was not 'true': false,
      error.stack: 
System.ArgumentException: Passed in value was not 'true': false
at Samples.AspNetMvc5.Controllers.ApiController.TransientFailure(String value),
      error.type: System.ArgumentException,
}
```

## Testing
This has been confirmed with the following test cases, on both ASP.NET Web API 2 applications and OWIN Web API 2 applications:
1. Adding a global message handler
2. Adding a per-route message handler

## Resources
[1] https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/http-message-handlers
[2] https://docs.microsoft.com/en-us/aspnet/web-api/overview/error-handling/web-api-global-error-handling