Fix support for building StackExchange Redis sample in latest package version (#8982)
## Summary of changes

Fix samples from breaking in latest version of StackExchange.Redis

## Reason for change

In 3.1.0, they introduce a new obsolete attribute, in preparation for
removing of a property.

```
error CS0619: 'CommandFlags.DemandSlave' is obsolete: 'Starting with Redis version 5, Redis has moved to 'replica' terminology. Please use DemandReplica instead, this will be removed in 3.2.'
```

## Implementation details

Gate the problematic API on 3.1.0+

## Test coverage

I'll cherry-pick this into
https://github.com/DataDog/dd-trace-dotnet/pull/8955 to confirm

## Other details

Creating as a separate PR rather than pushing directly to the test PR to
avoid the fact it can automatically get re-pushed