Add retries to build stages (#7039)
## Summary of changes

Adds `retryCountOnTaskFailure` to more _build_ stages

## Reason for change

The .NET SDK sometimes just crashes when we're trying to build, [e.g.
here](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=178522&view=logs&j=dc2ce868-6617-591d-f9a9-d163411addf1&t=40f45dbd-4ed6-5434-857e-8ac8503c967b)

```
Target CompileLinuxOrOsxIntegrationTests has thrown an exception
System.AggregateException: One or more errors occurred. (Process 'dotnet' exited with code 139.
   > /usr/bin/dotnet build /project/tracer/test/Datadog.Trace.ClrProfiler.IntegrationTests/Datadog.Trace.ClrProfiler.IntegrationTests.csproj --configuration Release --framework net6.0 --no-dependencies --packages /project/packages /property:Platform=AnyCPU /property:TestAllPackageVersions=true /nowarn:NU1701
   @ /project
```

To reduce the impact, we add more retries to the build stages. We
_don't_ generally want to auto-retry run stages, as these are generally
long, and will result in timeouts + may be "real" failures due to test
failures etc.

## Implementation details

- Add retries to the "build" parts of various integration test stages
- Split some tasks that were doing "build and run" into two separate
tasks, and add retries to them

## Test coverage

Unchanged, but hopefully improves pipeline reliability (I've
particularly noticed this on linux arm64 recently)

## Other details
<!-- Fixes #{issue} -->

<!-- ⚠️ Note: where possible, please obtain 2 approvals prior to
merging. Unless CODEOWNERS specifies otherwise, for external teams it is
typically best to have one review from a team member, and one review
from apm-dotnet. Trivial changes do not require 2 reviews. -->