Retry cloning branches. (#7057)
## Summary of changes

It has been [observed
](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=178792&view=logs&j=e864b932-3aad-5323-ff20-51096263ed14&t=79008bee-55ca-5a41-44bb-626ed34f8bcf&s=1880ad09-7d14-564c-a87d-6c2179a93667
) that git fetch and git clone can fail due to GH issues that we cannot
control. When that happens, the task is marked as green and the next
merge task will fail.

In this PR, a simple retry mechanism has been implemented to try to
recover from that error and make the task fail if it is not possible. In
the script, the git fetch and git checkout commands are combined with
&&. This means that the checkout will only proceed if the fetch is
successful. If either command fails, the script will not move to the
break statement and eventually exit with an error code.

This is the error:
```
Initializing repository at /mnt/vss/_work/1/s ...
Initialized empty Git repository in /mnt/vss/_work/1/s/.git/
Adding remote https://github.com/DataDog/dd-trace-dotnet ...
Force fetching master and nacho/HttpRequestUtilsFix ...
fatal: unable to access 'https://github.com/DataDog/dd-trace-dotnet/': The requested URL returned error: 502
Checking out nacho/HttpRequestUtilsFix...
error: pathspec 'nacho/HttpRequestUtilsFix' did not match any file(s) known to git
Resetting nacho/HttpRequestUtilsFix to origin/nacho/HttpRequestUtilsFix ...
fatal: ambiguous argument 'origin/nacho/HttpRequestUtilsFix': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Running git clean -ffdx ...

Finishing: checkout
```

## Reason for change

## Implementation details

## Test coverage

## Other details
<!-- Fixes #{issue} -->

<!-- ⚠️ Note: where possible, please obtain 2 approvals prior to
merging. Unless CODEOWNERS specifies otherwise, for external teams it is
typically best to have one review from a team member, and one review
from apm-dotnet. Trivial changes do not require 2 reviews. -->